rate: 10 
controller_list:
  - name: fake_mycobot_arm_controller
    type: interpolate
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
  - name: fake_mycobot_gripper_controller
    joints:
      - gripper_base_to_l_finger
initial:  # Define initial robot poses.
  - group: mycobot_arm
    pose: rest